samples:
   - JF136_S3
   - JF137_S4
   - JF144_S11
   - JF145_S12

bamPath: "/n/holyscratch01/macklis_lab/jfroberg/CellReports_round2/dedupBams"

RiboCode:
    metadata: "../nanoRibo-Seq/RunRiboCodeOnly/SCPN_meta.csv"
    modules: "Anaconda/5.0.1-fasrc02"
    shell_script: "../nanoRibo-Seq/scripts/separateRPbams.sh"
    annot_gtf: "/n/macklis_lab/users/jfroberg/gtfs/mm10_RiboCode_gtfs/RiboCode_annot.gtf"
    list_script: "../nanoRibo-Seq/scripts/bamFileList_script.sh"   
    comboScript: "../nanoRibo-Seq/scripts/combineORFcounts.sh"

ribotricer:
    gtf: "/n/macklis_lab/users/jfroberg/gtfs/Mus_musculus.GRCm38.95_chrNamed_headFix.gtf"
    fasta: "/n/macklis_lab/users/jfroberg/mtrDmm10/mm10_fasta_from_ucsc_complete.fasta"
    start_codons: "ATG,GTG,CTG,TTG"
    min_orf_length: 21
    cutoff: 0.369
    min_codons_valid_ratio: 0.1
